name: R-CMD-check

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false   # voorkomt dat een nieuwe push de vorige run annuleert

jobs:
  check:
    runs-on: ubuntu-latest     # stabieler en sneller dan macOS voor R
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
    steps:
      - uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          use-public-rspm: true   # binaire CRAN packages → veel minder build-gedoe

      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install system deps (curl/ssl/xml, vaak nodig)
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Install R deps
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - name: Check package
        uses: r-lib/actions/check-r-package@v2
        with:
          args: 'c("--no-manual","--as-cran")'
          upload-snapshots: true
          error-on: '"error"'   # faal enkel op errors, niet op warnings
